### ISSUE TITLE
Prerender enrolment flow

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#117]
Blocked on #82

**Comment by Brendonovich** [comment]
Might be worth using an API route + `renderToString` + `hydrate` manually for this, since we basically want it to be its own mini-app

**Comment by oscartbeaumont** [comment]
Yeah, I recon we use `renderToString` but forgo the `hydrate` cause that's hard and the flow doesn't benefit from SPA navigation (cause it has to hard link to external OAuth flow).
