### ISSUE TITLE
Router is broken in prod

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#130]
It's updating the URL but not the page content.

**Comment by Brendonovich** [comment]
idk man whole app is broken in prod for me

![Image](https://github.com/oscartbeaumont/forge/assets/14191578/46bdd196-5804-49a6-9a57-810f672a7c1d)

**Comment by oscartbeaumont** [comment]
![Screenshot 2024-02-10 at 11 08 14 am](https://github.com/oscartbeaumont/forge/assets/21004798/1e1a2cf7-e406-407b-9bbf-8a885f46e1b4)
Yeah that's my bad.
