### ISSUE TITLE
Domains 2.0

### ISSUE THREAD

**Issue by Brendonovich** [mattrax/Mattrax#174]
source domains from auth providers

- one auth provider per tenant
- multiple domains per auth provider
- domains can only be used by one auth provider at a time

> Do we disable the whole auth provider or just skip the domain?

Skip the domain and do the same 'this domain is in use by another tenant' warning

> I wonder if we require expressly enabling each domain in a checkbox under the auth provider

yes

**Comment by oscartbeaumont** [comment]
Handles #170.
