### ISSUE TITLE
Navbar underline offset after load.

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#210]
https://github.com/mattrax/Mattrax/assets/21004798/c9e068a8-94e4-441b-93e2-d40ed9c81fbf

It's also the wrong color.

**Comment by Brendonovich** [comment]
not happening to me 🤷

**Comment by oscartbeaumont** [comment]
https://github.com/mattrax/Mattrax/assets/21004798/b42e9960-7b79-4d6c-ab36-380a5d824fb8

It's defs happening in prod.

**Comment by Brendonovich** [comment]
skill issue

https://github.com/mattrax/Mattrax/assets/14191578/2af2f408-fef1-4c1e-90bd-d0c30273b4c0

**Comment by oscartbeaumont** [comment]
Might be a Chrome bug then. Safari doesn't seem to do it, or Brave as you showed.

**Comment by oscartbeaumont** [comment]
Looks like it's fixed itself. I wonder why that is but ehh.

**Comment by oscartbeaumont** [comment]
I think this is a problem with the Grammarly extension.
