### ISSUE TITLE
Create tenant dialog glitchy

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#229]
https://github.com/mattrax/Mattrax/assets/21004798/a7702f32-ac36-4950-99b2-c350bdd3f136

**Comment by Brendonovich** [comment]
hmm i can't reproduce this, might be another weird browser thing?

https://github.com/mattrax/Mattrax/assets/14191578/7a83aca8-fe4b-4db7-b9ca-c0ee3c27a671

**Comment by oscartbeaumont** [comment]
Chrome is just snorting crack.

**Comment by oscartbeaumont** [comment]
Looks like this animation is gone so this is fixed.
