### ISSUE TITLE
Production is stupidly slow

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#268]
Supabase is not performing well. Idk, if this is our fault or just Postgres.

I wonder of the overhead of creating DB connections is the problem?

MySQL + Cityscale:
![Screenshot_2024-04-21_at_10 49 56_AM](https://github.com/mattrax/Mattrax/assets/21004798/2a4405f6-1af6-4d10-b65c-228e8be1e980)
https://78c230c9.mattrax-bdc.pages.dev

Postgres + Supabase:
![Screenshot_2024-04-21_at_10 50 09_AM](https://github.com/mattrax/Mattrax/assets/21004798/a473e4b1-ddeb-4748-bbab-e010fb628a32)
https://cloud.mattrax.app

**Comment by oscartbeaumont** [comment]
This issue comes down to:
 - Creating Postgres connections is slower than just `fetch` to a connection pooler
 - Cloudflare Smart Placement only works on HTTP, not TCP protocols so the code is running away from the DB

**Comment by Brendonovich** [comment]
fixed by moving back to planetscale adapter
