### ISSUE TITLE
Policy builder goes blank after adding Apple configuration sometimes

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#301]
![Screenshot 2024-05-22 at 6 49 37 PM](https://github.com/mattrax/Mattrax/assets/21004798/ac193ff4-a756-4037-bdb4-e24a7616a94c)

**Comment by Brendonovich** [comment]
fixed by adding `position: relative` to the checkbox input element since the `position: absolute` inline style causes this.
