### ISSUE TITLE
Policy editor crashes on direct load

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#322]
It's fine when doing an SPA navigation but not what directly reloading the page.

Safari:

[https://github.com/mattrax/Mattrax/assets/21004798/e5032d23-b2d2-46fe-b706-555edd8d97ed](https://github.com/mattrax/Mattrax/assets/21004798/e5032d23-b2d2-46fe-b706-555edd8d97ed)

Chrome:

![Screenshot 2024-06-03 at 1 16 35 PM](https://uploads.linear.app/be28d5fc-bd76-4650-9423-6653ded376ff/cca543f8-6cbe-4488-8cc4-7027a49f080b/3143bc52-0042-4e7f-9b6d-82d3eccf5514?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JlMjhkNWZjLWJkNzYtNDY1MC05NDIzLTY2NTNkZWQzNzZmZi9jY2E1NDNmOC02Y2JlLTQ0ODgtOGNjNC03MDI3YTQ5ZjA4MGIvMzE0M2JjNTItMDA0Mi00ZTdmLTliNmQtODJkM2VjY2Y1NTE0IiwiaWF0IjoxNzE3NTkwOTI4LCJleHAiOjMzMjg4MTUwOTI4fQ.gxoga6drAYn1IxsDSqFrUZEEG9QTbE3l2H2L2zqmQYU "=976x")

**Comment by oscartbeaumont** [comment]
Sometimes the data just doesn't load on the right?

I wonder if that's related to why the checkbox's sometimes stay disabled.

**Comment by Brendonovich** [comment]
Pretty sure this is fixed, there was a default value missing
