### ISSUE TITLE
Breadcrumb loads in wierd in prod

### ISSUE THREAD

**Issue by oscartbeaumont** [mattrax/Mattrax#369]
https://github.com/mattrax/Mattrax/assets/21004798/f44138a3-f3a6-4d69-b6ab-a19e6e0c5a1d

**Comment by Brendonovich** [comment]
afaict this is solid being weird when suspending on one resource and then another in the tenant breadcrumb

**Comment by Brendonovich** [comment]
Fixed by b883107d4b4a1c568cd59d08a8a8e9c5b262d57a
